### ISSUE TITLE
Architecture Design: Making cron-server fault tolerant

### ISSUE THREAD

**Issue by samparsky** [victorlenerd/cron-server#13]
*Possible Architecture Design*

i. You have a leader node that schedules cron tasks to child nodes via a round robin method
if the leader node fails a new leader is elected via Raft consensus.

ii. It's possible to use sharding type algorithm to designate tasks among child nodes instead of round robin.

ii.  It can also take care of dependent cron jobs i.e. A job must run prior to B

iv. On completion of a cron job a child node must report back to the leader node for successful task completion or if an error occurred it should notify the leader node

v. If a cron job exceeds a specified time limit the leader node can query the child node to know the status of job and if the child node has crashed / is offline can schedule the task back to another child node for completion

PS: child nodes here could just be worker threads 
This is still a thought in progress 😄

**Comment by victorlenerd** [comment]
I've thought of how I could use the raft consensus model to make the system distributed, I've also considered using CockroachDB and only making the database distributed. 

For now, the focus is on getting a simple working prototype without the fault-tolerant feature.
